### ISSUE TITLE
使用说明有一处语法错误

### ISSUE THREAD

**Issue by Septembers** [dmscode/my-wiki#1]
![](https://cloud.githubusercontent.com/assets/3842474/7445305/c72c5d60-f1df-11e4-838b-227df956e9c8.png)

正确写法应当是：
> `[https://github.com/learning/SublimeServer](https://github.com/learning/SublimeServer)`

或者是：
> `<https://github.com/learning/SublimeServer>`

see https://github.com/dmscode/my-wiki/blame/gh-pages/data/demo.md#L9
see http://dmscode.github.io/my-wiki/?name=demo

--------------------

另外补充建议：代码高亮建议使用monospace字体

**Comment by dmscode** [comment]
语法错误我本地是修改了的，但是可能忘记了推送。

然后今天在折腾系统，只好晚些修改了，字体会一并修改，感谢您的提醒和建议～
